module.exports = {
	emptySchema:{

	},

	noReadOnlySchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"type":"string",
				"required":true
			},
			"c":{
				"type":"string",
				"required":true,
				"readonly":false
			},
			"d":{
				"type":"string",
				"required":false
			}
		}
	},

	simpleSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"type":"string",
				"required":false,
				"readonly":true
			},
			"c":{
				"type":"string",
				"required":true,
				"readonly":false
			},
			"d":{
				"type":"string",
				"required":false,
				"readonly":true
			}
		}
	},

	nestedSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"required":true,
				"type":"object",
				"properties":{
					"d":{
						"type":"string",
						"required":false,
						"readonly":true
					},
					"e":{
						"type":"string",
						"required":true
					}
				}
			},
			"c":{
				"type":"string",
				"required":false,
				"readonly":true
			}
		}
	},

	arrayReadOnlyItemsSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"required":true,
				"type":"array",
				"items":{
					"required":false,
					"readonly":true,
					"type":"object",
					"properties":{
						"d":{
							"type":"string",
							"required":false,
							"readonly":true
						},
						"e":{
							"type":"string",
							"required":false
						}
					}
				}
			},
			"c":{
				"type":"string",
				"required":false,
				"readonly":true
			}
		}
	},

	arraySchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"required":true,
				"type":"array",
				"items":{
					"required":true,
					"type":"object",
					"properties":{
						"d":{
							"type":"string",
							"required":false,
							"readonly":true
						},
						"e":{
							"type":"string",
							"required":true
						}
					}
				}
			},
			"c":{
				"type":"string",
				"required":false,
				"readonly":true
			}
		}
	},

	arrayNestedSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"required":true,
				"type":"array",
				"items":{
					"required":true,
					"type":"object",
					"properties":{
						"b":{
							"required":true,
							"type":"object",
							"properties":{
								"c":{
									"type":"string",
									"required":false,
									"readonly":true
								},
								"d":{
									"type":"string",
									"required":true
								}
							}
						}
					}
				}
			}
		}
	},

	arrayAtRootSchema:{
		"description":"Schema that contains an array at root level",
		"required":true,
		"type":"array",
		"items":{
			"description":"The id",
			"required":true,
			"type":"object",
			"properties":{
				"id":{
					"description":"Must be a valid id",
					"required":false,
					"readonly":true,
					"type":"string",
					"example":"503714a74400b29809000004"
				}
			}
		}
	},

	// DecimalSchema

	noDecimalSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"type":"string",
				"required":true
			},
			"c":{
				"type":"string",
				"required":true,
				"readonly":false
			},
			"d":{
				"type":"string",
				"required":false
			}
		}
	},

	simpleDecimalSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"type":"number",
				"required":false,
				"maxDecimal":2
			},
			"c":{
				"type":["null","number"],
				"required":true
			},
			"d":{
				"type":["null","number"],
				"required":false,
				"maxDecimal":3
			}
		}
	},

	nestedDecimalSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"required":true,
				"type":"object",
				"properties":{
					"d":{
						"type":"number",
						"required":false,
						"maxDecimal":2
					},
					"e":{
						"type":"string",
						"required":true
					}
				}
			},
			"c":{
				"type":"number",
				"required":false,
				"maxDecimal":3
			}
		}
	},

	arrayDecimalSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"number",
				"required":true
			},
			"b":{
				"required":true,
				"type":"array",
				"items":{
					"required":true,
					"type":"object",
					"properties":{
						"d":{
							"type":"number",
							"required":false,
							"maxDecimal":2
						},
						"e":{
							"type":"string",
							"required":true
						}
					}
				}
			},
			"c":{
				"type":"number",
				"required":false,
				"maxDecimal":3
			}
		}
	},

	arrayNestedDecimalSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"required":true,
				"type":"array",
				"items":{
					"required":true,
					"type":"object",
					"properties":{
						"b":{
							"required":true,
							"type":"object",
							"properties":{
								"c":{
									"type":"number",
									"required":false,
									"maxDecimal":2
								},
								"d":{
									"type":"string",
									"required":true
								}
							}
						}
					}
				}
			}
		}
	},

	arrayAtRootDecimalSchema:{
		"description":"Schema that contains an array at root level",
		"required":true,
		"type":"array",
		"items":{
			"description":"The id",
			"required":true,
			"type":"object",
			"properties":{
				"a":{
					"required":false,
					"maxDecimal":2,
					"type":"number"
				}
			}
		}
	},

	schemaRootObjectWithoutPropertiesSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object"
	},

	schemaObjectWithoutPropertiesSchema:{
		"description":"Simple object",
		"required":true,
		"type":"object",
		"properties":{
			"a":{
				"type":"object",
				"required":true
			}
		}
	}
};
